### ISSUE TITLE
Hilight compatible blood bags

### ISSUE THREAD

**Issue by carloborreo** [Mephiles/torntools_2#104]
It would be nice if blood bags were hilighted in two different ways:

1) My blood type (for instance, in green)
2) Blood that I could use (for instance, in yellow)

This way, we could easily switch to a compatible blood type, if the stock of my blood type is scarce.
Optional: if we also display the market value of the bags, I could choose the cheapest, compatible blood type.

**Comment by DeKleineKobini** [comment]
Honestly, I don't see the use for this, either you can use it or not.

And item value is already a feature.
