### ISSUE TITLE
Toggle chat.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_2#13]
Allow to disable chats being shown at all.

- [ ] Setting @ Chat = Show toggle chat button.
- [ ] Setting @ Chat = Hide chats.
- [ ] Add toggle button, if enabled.
- [ ] Actually hide chats, if enabled.

**Comment by Mephiles** [comment]
An extra setting for this feature:
- option to only hide PMs. meaning chats like Faction, Company, etc. will be ignored and shown always.

**Comment by DeKleineKobini** [comment]
On hold due to chats 2.0 coming 'soon'.
