### ISSUE TITLE
Show link for TT Settings in Sidebar

### ISSUE THREAD

**Issue by Sashank999** [Mephiles/torntools_2#144]
Show settings on the page.
- Add as an 'area' in the sidebar.
  - Use custom classes, so Torn's code doesn't break it.
  - Make sure it's position is correct when leaving the hospital/jail.
- Hide content and show TornTools settings.
  - When quitting, remove settings and show content again.

v5 version:
![image](https://user-images.githubusercontent.com/76554862/117459723-58224580-af69-11eb-9009-bc371e56c758.png)

**Comment by Mephiles** [comment]
f you are hospitalized then clicking on the link redirects you to index.php which redirects you to hospital.php and the settings page isn't shown.

**Comment by DeKleineKobini** [comment]
Instead of it being a link, it should work like the travel table while flying: hide (some) content and show the feature.

**Comment by Mephiles** [comment]
That's a good idea, Torn uses the content container on every page if I remember correctly so just clearing it should work.
