### ISSUE TITLE
Shorten armory logs.

### ISSUE THREAD

**Issue by C13L0** [Mephiles/torntools_2#178]
* Shorten armory logs (group multiple entries into one)

**Comment by DeKleineKobini** [comment]
Not sure how doable this is due to the React logs.

@Mephiles @Sashank999

**Comment by Mephiles** [comment]
There are no pages anymore indeed but a long selfexpanding list. I think we can close this issue unless someone thinks of a solution that's viable.

**Comment by Allo101** [comment]
how about an option to export to CSV for all visible lines?

**Comment by DeKleineKobini** [comment]
TODO: Add notice in changelog of it's removal.

**Comment by Mephiles** [comment]
> how about an option to export to CSV for all visible lines?

I don't think that's useful as it would still need some skill to group/count the listings by player, action & item.

**Comment by DeKleineKobini** [comment]
Added it's removal in the changelor with 0576e9ca2a9d6951b57c07e03bb208602c4b6ce8
