### ISSUE TITLE
Custom links.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_2#23]
Custom links.

- [x] Setting @ Sidebar = Custom links. (row based - name + color).
- [x] Link presets.
- [x] Change place to display them.
  - [x] Above areas.
  - [x] Between areas.
  - [x] Under areas.
- [ ] Make mobile friendly.

**Comment by DeKleineKobini** [comment]
Except for mobile, they work.

**Comment by Mephiles** [comment]
Proposed changes:
 - [ ] Replace red background with wither `border: 1px solid white` or `border-left: 1px solid white` (dark-mode; didn't check light-mode)
 - [ ] Remove "ghost row" when dragging rows, as I understood it can only be done using JS event listeners and replacing the image with a transparent one
