### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_2#24]
Popup information.

- [x] Setting @ Popup = Enable tabs.
- [x] Setting @ Popup = Default tab.
- [x] Page - Dashboard
  - [x] Option to (un)mute notifications.
  - [x] Show country.
  - [x] Show status.
  - [x] Show permanent bars (energy, nerve, happy and life)
  - [x] Show situational bars (chain, travel).
  - [x] Show cooldowns (drug, booster and medical).
  - [x] Show messages, events and on hand cash.
- [x] Page - Market
  - [x] Search for items.
  - [x] Show item market and bazaar prices.
- [x] Page - Stocks
  - [x] Display all owned blocks.
  - [x] Allow searching for all stocks.
  - [x] Show benefit info.
  - [x] Set alerts.
- [x] Page - Calculator
  - [x] Search for items.
  - [ ] Adjust price.
- [x] Page - Stakeouts

**Comment by DeKleineKobini** [comment]
Calculator will be left out currently.

**Comment by DeKleineKobini** [comment]
Or make a revamped version.

**Comment by DeKleineKobini** [comment]
Stakeouts will be getting their own page.

**Comment by Mephiles** [comment]
Proposed changes:
 - [ ] As all times will be on exactly 00 seconds then seconds could be removed from "Show full time of bars on hover."
 - [ ] Stocks tab could use a custom slimmer scrollbar because 1) it would look better if it matched with the rest of the style and 2) it would reduce width bobbing

**Comment by DeKleineKobini** [comment]
> * [ ]  As all times will be on exactly 00 seconds then seconds could be removed from "Show full time of bars on hover."

Not sure about this one, as we also show the countdown in mm:ss, so only showing hh:mm could be a bit confusing.

> * [ ]  Stocks tab could use a custom slimmer scrollbar because 1) it would look better if it matched with the rest of the style and 2) it would reduce width bobbing

Not sure if a custom scrollbar is a great idea. From what I know, they can be a bitch on some browsers. Just some minor changes like a color should be possible.
