### ISSUE TITLE
Stock filter

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_2#287]
- Filter stocks on certain criteria.
  - Name + acronym
  - Dividend
    - is active/passive reward
    - own dividend (yes/no; none selected)
    - ready dividend (yes/no; none selected)
  - Own stocks in the specific stock.
  - Profit/loss

Should be implemented like the [jail filter](https://github.com/Mephiles/torntools_2/blob/master/extension/scripts/features/jail-filter/ttJailFilter.js). [v5 code](https://github.com/Mephiles/torntools_extension/blob/master/torntools/scripts/content/stockexchange/ttStockexchange.js#L45) could provide help.

**Comment by Sashank999** [comment]
This needs me to own a benefit block, which I don't.
