### ISSUE TITLE
Show creator indication on profile.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_2#290]
- Show TT creator indication on profile.

**Comment by DeKleineKobini** [comment]
@Mephiles Should we also extend this to contributors. If yes, on what criteria, because adding it for every since contributor seems overkill to me.

**Comment by Mephiles** [comment]
Seems like I have missed this question here, sorry.

I think we can extend this to the same circle of people that are listed on the settings page.
