### ISSUE TITLE
About TornTools.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_2#296]
- [x] Show current version.
- [x] Show used disk space (chromium only?)
- [x] Brought to you by ... the team
- [x] Link to source code.
  - Licences under the GNU ....
- [x] Link to Discord invite.
- [x] Link to forum post.
- [x] Direct suggestions and bug reports to the Discord or the forum post.
  - "Include screenshots of the bug"
  - "Include screenshots of the console."
    - Open with CTRL + SHIFT + J.
    - Open with right click -> inspect element -> console.
    - Open with F12 or CTRL + SHIFT + I -> console.
- [x] Donation links.

**Comment by DeKleineKobini** [comment]
> Brought to you by ... the team
@Mephiles How should we do this one?

> Donation links.
@Mephiles I always find this a though one.

**Comment by Mephiles** [comment]
> Brought to you by ... the team
I think I would like to list some names for sure. Something like this:
Mephiles [..] (Creator, Developer)
DeKleineKobini [..] (Developer)
Bandirao [..] (Developer)
Allo [..]
_And Everyone else who helped us beta-test; provided feedback, suggestions, bug reports; or just generally helped out in the Discord._

> Donation links.
Something like this:
TornTools is free to use but if you feel like giving back to the developers then feel free to donate in-game or via one of those PayPal links:
Mephiles [PayPal link]
DeKleineKobini [PayPal link]
Bandirao [PayPal link]
Allo [PayPal link]


P.S.
I haven't kept track of it that much but when v6.0 is released and we feel like AllMight has made noticeable contributions then I have nothing against adding him to the list.

Also, if someone I put on the list, feels like they don't want to be there (in either one) then I'm not forcing either.

I couldn't think of a title to give to Allo, if he can think of smth then we can add it.

I thought about it for a sec but not sure if it'd be worth it setting up a main PayPal account to distribute any contributions evenly among all listed PayPal links? It certainly won't be like the main income for any of the people listed but I think it's a nice gesture to have these links available and it'll be like "Pay for my coffee" kind of feeling when you get those 4-5 euros.

**Comment by DeKleineKobini** [comment]
> P.S.
> I haven't kept track of it that much but when v6.0 is released and we feel like AllMight has made noticeable contributions then I have nothing against adding him to the list.

For now, I don't think he should be added, but if he keeps contributing more that could change yeah.

> Also, if someone I put on the list, feels like they don't want to be there (in either one) then I'm not forcing either.

As Allo stated on Discord, he doesn't want donations. So I've made it possible to simply not provide donation links but still be shown as a 'core member'. Other contributors aren't shown on the about page.

> I thought about it for a sec but not sure if it'd be worth it setting up a main PayPal account to distribute any contributions evenly among all listed PayPal links? It certainly won't be like the main income for any of the people listed but I think it's a nice gesture to have these links available and it'll be like "Pay for my coffee" kind of feeling when you get those 4-5 euros.

Not sure, would be quite some work, and probably pretty expensive due to paying taxes twice I think?
