### ISSUE TITLE
Abroad reminder notifications

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_2#347]
Problem: For example when you're abroad and get the notification that you have landed but you were not at the computer that moment.

Solution: Add option for reminders so once a minute if you still haven't started flying back, another notification is sent out.

There might other such places, couldn't think of any right now though.

(Not sure about default value here)

**Comment by DeKleineKobini** [comment]
Would have to be disabled by default, as it's pretty annoying.

**Comment by DeKleineKobini** [comment]
Still thinking that this is only annoying as ****. I don't see anyone actually using it. It might sound nice, until your destination is out of stock of all profitable items.

**Comment by DeKleineKobini** [comment]
Moved to normal repo.
