### ISSUE TITLE
Hide unimportant information boxes

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_2#358]
There are a few information sections around Torn that have no actual need to be there. So just to clean up the pages a bit, maybe these could be hidden?

(Not hidden by default)

Some examples:
 - City Shops' information sections at the top
 - Crimes page information section
 - Vault 1B$ warning section (I don't think this is that crucial of information that needs to be reminded to the player every time)
 - Item market info section

Not saying they're really annoying or don't fit there, just some people prefer to have pages as clean as possible.

**Comment by DeKleineKobini** [comment]
For now, I would put this as a target for v6.1. If we have enough time left, we can put it in v6.0, but I don't think it should be a priority.

**Comment by DeKleineKobini** [comment]
Moved to normal repo.
