### ISSUE TITLE
Attack history.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_2#36]
Attack history.

- [x] Setting @ Global = Keep attack history.
- [x] Show attack history on separate page.
  - [x] Reset attack history.
  - [x] Show numbers in %.

**Comment by Mephiles** [comment]
Maybe could add a simple hover highlighting so it's easier to view a specific row?

**Comment by DeKleineKobini** [comment]
Going to close this, as it's basically part of #291 and the other part is done.
