### ISSUE TITLE
Faction upgrades - steadfast actual totals

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_2#367]
Under steadfast, for example speed & strength. Only one can be upgraded over 10% at once. Clicking on the in-progress upgrade shows the training progress:
![image](https://user-images.githubusercontent.com/20304303/126833795-ac078b20-a0cc-405b-b2ad-1a23b8fc891e.png)

But factions like to rotate them. So they unset the Speed and then set the Strength upgrades over 10%. Would be great to see the actual totals when clicking on 10% upgrades (or any other upgrade for that matter).

Screenshot from Doctorn:
![image](https://user-images.githubusercontent.com/20304303/126833896-86570472-5de5-4b50-a9fd-04e27910aeb2.png)

**Comment by DeKleineKobini** [comment]
![image](https://user-images.githubusercontent.com/7302579/132948847-e1d2da2f-7c86-49df-a9ff-5b3457cdb212.png) is this what you mean?

**Comment by Mephiles** [comment]
> ![image](https://user-images.githubusercontent.com/7302579/132948847-e1d2da2f-7c86-49df-a9ff-5b3457cdb212.png) is this what you mean?

Didn't notice the 5 at first on the first number but yes exactly. For us it would be somewhere around 14mil/5mil.

But adding the number there might be confusing? What about like Doc, at the bottom saying "Total: ..." because it would make more sense as the number is calculated based on all the contributors. Other alternative would be to add it to the end as ".. training (7mil/5mil)" but that might look weird on the actual in-progress challenges where there's already the actual total?

**Comment by DeKleineKobini** [comment]
Moved to normal repo.
