### ISSUE TITLE
Racing timer in popup

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_2#371]
Add racing timer in the popup. Could be like the cooldowns but maybe a timer bar would be better? Like travel bar so it doesn't show 100% of the time.

Not sure if the necessary information is available via API.

**Comment by DeKleineKobini** [comment]
We can detect races using the icon api.

**Comment by DeKleineKobini** [comment]
> Like travel bar so it doesn't show 100% of the time.
Then how would we decide not to show it anymore?

**Comment by Mephiles** [comment]
> > Like travel bar so it doesn't show 100% of the time.
> 
> Then how would we decide not to show it anymore?

I think that if there is the race timer then show it and if it reaches 0 then don't show it. There's an event notification anyway when you finish the race so it won't be that weird imo?

**Comment by DeKleineKobini** [comment]
So based on the @Mephiles, we will scrap this right?

**Comment by Mephiles** [comment]
Yea we can scrap it for now. If it ever comes back up again then we can come back to it
