### ISSUE TITLE
City shops filters

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_2#382]
Not 100% necessary but a QoL thing as TT has added lots of filters everywhere.

Add filters to city shops where you could filter by
1) Stock: min-max (auto-populated)
2) Buy price: min-max (auto-populated)
3) Profit: min-max (auto-populated)

As I said, not anything critical, but it'd be much more effective when the negative profit items & items with stock less than 100 are automatically hidden as you load the page for example.

**Comment by DeKleineKobini** [comment]
I've thought about it a bit, and I can't get myself to think of the proposed filters as useful.

I would say:

> Hide items with a loss.
> Hide items under 100 stock.

**Comment by Mephiles** [comment]
Yea sure, these would be the main 2 filters to use so

**Comment by Sashank999** [comment]
> I've thought about it a bit, and I can't get myself to think of the proposed filters as useful.
> 
> I would say:
> 
> * Hide items with a loss.
> * Hide items under 100 stock.

I'm doing only these two.
