### ISSUE TITLE
Stakeouts notification - offline time

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_2#385]
Add stakeouts option for X hours offline notification.

The main use case would be to attack the player after a ghost trade has ended. So the notification can also be a fixed 6h instead of a configurable time.

If no other use cases can be thought of then I'd say go with the fixed 6h for simplicity.

**Comment by DeKleineKobini** [comment]
I'm against adding a feature that's focused on mugging, especially after a ghost trade expired.

**Comment by Mephiles** [comment]
Isn't the main point of stakeouts attacking? Like "is okay" - for bounties for example. "Life drops below" and "lands" for general attacking.

They can be used otherwise as well like if you're waiting for your friend to land or smth but mostly they are attack-based and therefore also money-based (bounties, mugging).
