### ISSUE TITLE
Disable job specials

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_2#394]
Add UI option to turn off some job specials to not waste money on them accidentally. Some specials have similar bonuses like `X nerve` or `X energy`. This would avoid clicking on the wrong thing accidentally.

**Comment by DeKleineKobini** [comment]
I don't see how we could this work without it being a disgrace for UX. A potential solution for the issue is for the user to read ....

**Comment by DeKleineKobini** [comment]
Still want to go ahead with this one @Mephiles? I still think we shouldn't.

**Comment by Mephiles** [comment]
No, we can scrap this also for now
