### ISSUE TITLE
Enable Developer features.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_2#4]
Show and use a custom console.

- [x] Advanced Setting @ General = Enable developer features. 
- [ ] Show custom console on the page.

**Comment by DeKleineKobini** [comment]
Might scrap this, as I can debug Kiwi now.

**Comment by DeKleineKobini** [comment]
Since debugging on Kiwi is possible now, this will be removed.

**Comment by Mephiles** [comment]
I think that the eye icon is not the best solution as there aren't many advanced options available.

I propose removing the eye icon as a global advanced option and add a little "advanced" text-link to the pages where advanced options are available. And furthermore, the advanced options should all appear after the "advanced" text not mix between normal options like the eye does now.

**Comment by DeKleineKobini** [comment]
There aren't many advanced options, but the ones that are there have the potential to break the extension without them knowing why.
