### ISSUE TITLE
Total education time left

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_2#442]
On educations page, show the total time left until all courses are completed. Should be achievable via the API.

Probably should show the time left in the format of `X years X months X days ... (2022.03.04)`

**Comment by DeKleineKobini** [comment]
I don't agree on this one. It's not really relevant to know either, as near the end, most of it is just filler.

**Comment by Mephiles** [comment]
I'd think it's fun to see some kind of estimate. Not really something to use daily but would be nice to see how far you are from completing everything

**Comment by Sashank999** [comment]
This isn't the feature I think it is. Accidentally assigned myself.

**Comment by DeKleineKobini** [comment]
Moved to normal repo.
