### ISSUE TITLE
Jail filters

### ISSUE THREAD

**Issue by C4LLZ** [Mephiles/torntools_2#72]
- [ ] Settings @ Jail = Jail Filters.
- [ ] Activity Tracker 
- [ ] Faction Selector
- [ ] Time left in Jail 
- [ ] Level Filter
- [ ] Score Filter

**Comment by Mephiles** [comment]
When coding this then the Score could be determined by the new formula.

**Advanced Jail Bust Guide** by **Nosy [890872]**: [link](https://www.torn.com/forums.php#/p=threads&f=61&t=16192039&b=0&a=0)

**Tl;DR**
difficulty = level * (time + 3);  // Time is in hours; difficulty == score (higher is harder)
