### ISSUE TITLE
Only show safe crimes.

### ISSUE THREAD

**Issue by C4LLZ** [Mephiles/torntools_2#80]
Only show safe crimes.
- Make sure to research the safe crimes good.

**Comment by DeKleineKobini** [comment]
Safe crimes aren't really that popular anymore, maybe this should be scrapped? @Mephiles

**Comment by Mephiles** [comment]
I agree, let's put this aside until people show their interest in it. Crimes 2.0 is coming soon as well anyway.. right...?
